---
title: "R Notebook"
output: html_notebook
---


```{r}
library(reticulate)
#use_python("/usr/bin/python3")
#library(raster)
library(SpaDES)
basenames = c('tsa40','tsa41')
basename <- list(c("tsa40"))
setPaths(modulePath = 'modules',
         inputPath = 'inputs',
         outputPath = 'outputs',
         cachePath = 'cache')
paths <- getPaths()
modules <- list('spades_ws3_dataInit', 'spades_ws3')
base.year <- 2015

horizon <- 1
times <- list(start = 0, end = horizon - 1)


objects <-  list()
params <- list(spades_ws3_dataInit = list(basenames = basename,
                                          tifPath = 'tif',
                                          hdtPath = 'hdt',
                                          hdtPrefix = 'hdt_',
                                          .saveInitialTime = 0,
                                          .saveInterval = 1,
                                          .saveObjects = c("landscape"),
                                          .savePath = file.path(paths$outputPath, "landscape")),
               spades_ws3 = list(basenames = basename,
                                 tifPath = 'tif',
                                 hdtPath = 'hdt',
                                 scheduler.mode = 'areacontrol',
                                 horizon = 1))
```

```{r}
sim <- simInit(paths=paths, modules = modules, times=times, params= params, objects = objects)
simOut <- spades(sim, debug=TRUE)

```


